#!/bin/bash

if type -p java; then
    echo found java executable in PATH
#    _java=java
elif [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]];  then
    echo found java executable in JAVA_HOME     
#    _java="$JAVA_HOME/bin/java"
else
    echo Installing Oracle JDK 7 ...  
    sudo apt-get update && sudo apt-get install oracle-java7-jdk
fi

sudo chmod +x /usr/local/bin/indiecity/InstalledApps/multi-snake/Full/multi-snake-0.2.0-standalone.jar
